---
# tasks file for maven-role

# I had to change the name of the package
- name: sudo apt install -y python-software-properties
  apt: pkg=software-properties-common state=present

# I had to use the package instead of the apt-repository
- name: sudo add-apt-repository ppa:webupd8team/java
  apt: pkg=openjdk-8-jdk state=present

- name: sudo apt get update
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: sudo apt-get install default-jdk
  apt: pkg=default-jdk state=present

- name: cd /home/edureka/Downloads/ && wget http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  get_url:
    url: http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    # I Used the actual home folder
    dest: /home/ubuntu/

- name: cd /opt/ && sudo tar -xzvf /home/edureka/Downloads/apache-maven-3.3.9-bin.tar.gz
  unarchive:
    src: "/home/ubuntu/apache-maven-3.3.9-bin.tar.gz"
    dest: "/opt"
    remote_src: yes

- name: sudo update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.3.9/bin/mvn 1001
  command: update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.3.9/bin/mvn 1001